"""Tests for tools/test_stack.py, which installs what the tests run on.

It is run by CI before anything else and by whoever sets up a checkout. What
it installs cannot be tried here; how it reads Home Assistant's own list of
versions, and what it says when the result is not what that list dictates,
can.
"""

import importlib.metadata
import importlib.util
import json
from pathlib import Path
import re
from types import ModuleType
from typing import Any

import pytest
import yaml

_ROOT = Path(__file__).resolve().parent.parent

# The shape of homeassistant/package_constraints.txt: exact pins, ranges, a
# few packages blocked by an impossible version, comments.
_CONSTRAINTS = """\
# Automatically generated by gen_requirements_all.py, do not edit

aiodhcpwatcher==1.2.1
aiousbwatcher==1.1.2
bleak-retry-connector==4.6.1
bleak==3.0.2
dbus-fast==5.0.22
habluetooth==6.26.5
serialx==1.8.2

# Constrain something to a range
grpcio>=1.75.1
uv>=0.9

# Never installed
enum34==1000000000.0.0
"""
_DICTATED = {
    "aiousbwatcher": "1.1.2",
    "serialx": "1.8.2",
    "dbus-fast": "5.0.22",
    "bleak": "3.0.2",
    "bleak-retry-connector": "4.6.1",
    "habluetooth": "6.26.5",
}


@pytest.fixture(scope="module")
def stack() -> ModuleType:
    """Load tools/test_stack.py, which is a script and not part of any package."""
    spec = importlib.util.spec_from_file_location(
        "glowrium_test_stack", _ROOT / "tools" / "test_stack.py"
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_what_home_assistant_dictates_is_read_from_its_own_list(
    stack: ModuleType,
) -> None:
    """The six libraries the tests lean on, and nothing else from the list."""
    assert stack.dictated(_CONSTRAINTS) == _DICTATED


def test_a_name_is_read_the_way_pip_reads_it(stack: ModuleType) -> None:
    """Case, and a dash, a dot or an underscore, do not make another package."""
    spelt = _CONSTRAINTS.replace("dbus-fast==", "Dbus_Fast==")
    assert stack.dictated(spelt) == _DICTATED


@pytest.mark.parametrize("gone", ["serialx==1.8.2", "bleak==3.0.2"])
def test_a_library_home_assistant_no_longer_dictates_is_named(
    stack: ModuleType, gone: str
) -> None:
    """Then this script is out of date, and guessing a version is not the answer."""
    name = gone.split("==", maxsplit=1)[0]
    with pytest.raises(SystemExit, match=rf"\b{name}\b"):
        stack.dictated(_CONSTRAINTS.replace(f"{gone}\n", ""))


def test_a_library_given_as_a_range_is_not_dictated(stack: ModuleType) -> None:
    """A range is not a version to install, and is reported as missing."""
    with pytest.raises(SystemExit, match="habluetooth"):
        stack.dictated(_CONSTRAINTS.replace("habluetooth==6.26.5", "habluetooth>=6.26"))


def test_a_library_not_at_the_dictated_version_is_named(stack: ModuleType) -> None:
    """Which one, what it is, and what it should be: the run fails on this."""
    assert stack.astray(_DICTATED, _DICTATED.get) == []

    newer = _DICTATED | {"bleak": "3.1.0"}
    assert stack.astray(_DICTATED, newer.get) == [
        "bleak is 3.1.0, and Home Assistant dictates 3.0.2"
    ]

    absent = dict.fromkeys(_DICTATED) | {"bleak": "3.0.2"}
    said = stack.astray(_DICTATED, absent.get)
    assert len(said) == 5
    assert "serialx is not installed, and Home Assistant dictates 1.8.2" in said


def test_the_oldest_stack_is_one_exact_release_of_the_test_plugin() -> None:
    """The one version written by hand: Home Assistant, by the plugin's number."""
    text = (_ROOT / "constraints-oldest.txt").read_text()
    pins = [line for line in text.splitlines() if line and not line.startswith("#")]
    assert len(pins) == 1
    assert re.fullmatch(
        r"pytest-homeassistant-custom-component==\d+\.\d+\.\d+", pins[0]
    )


def test_the_oldest_stack_is_the_minimum_this_project_declares() -> None:
    """What hacs.json promises is what the oldest leg tests - checked on that leg.

    The plugin's number says nothing of the Home Assistant inside it, so the
    pin cannot be held to the promise by reading files. Where the installed
    plugin is the pinned one, the Home Assistant beside it can be.
    """
    pinned = (_ROOT / "constraints-oldest.txt").read_text().rsplit("==", 1)[1].strip()
    plugin = "pytest-homeassistant-custom-component"
    if importlib.metadata.version(plugin) != pinned:
        pytest.skip("this is not the oldest stack")

    declared = json.loads((_ROOT / "hacs.json").read_text())["homeassistant"]
    assert importlib.metadata.version("homeassistant") == declared


def test_no_version_home_assistant_dictates_is_written_in_the_repository(
    stack: ModuleType,
) -> None:
    """A version written here goes stale the day Home Assistant moves.

    That is what made collection fail with an ImportError until a file was
    edited by hand - and what had CI test a library version no installation
    of that Home Assistant runs.
    """
    for name in ("requirements-test.txt", "constraints-oldest.txt"):
        named = {
            re.split(r"[=<>~!\[; ]", line, maxsplit=1)[0].lower().replace("_", "-")
            for line in (_ROOT / name).read_text().splitlines()
            if line and not line.startswith("#")
        }
        assert not named & set(stack.DICTATED), name
        assert not named & set(stack.COMPANIONS), name


def test_each_stack_is_installed_from_the_same_requirements(
    stack: ModuleType,
) -> None:
    """The oldest is the newest with one constraint more - and nothing else."""
    newest = stack.first_install("newest")
    oldest = stack.first_install("oldest")
    assert str(_ROOT / "requirements-test.txt") in newest
    assert str(_ROOT / "requirements-test.txt") in oldest
    assert str(_ROOT / "constraints-oldest.txt") in oldest
    assert str(_ROOT / "constraints-oldest.txt") not in newest
    # An environment that has an older Home Assistant moves on to the newest.
    assert "--upgrade" in newest
    with pytest.raises(SystemExit, match="oldest"):
        stack.first_install("latest")


def _yaml(path: str) -> Any:
    return yaml.safe_load((_ROOT / path).read_text())


_ONCE = (
    "github.event_name != 'pull_request' || "
    "github.event.pull_request.head.repo.full_name != github.repository"
)


def test_ci_runs_every_stack_the_script_installs(stack: ModuleType) -> None:
    """Both legs, each with the script, and neither let off if it fails."""
    job = _yaml(".github/workflows/test.yml")["jobs"]["test"]

    assert job["strategy"]["matrix"]["stack"] == list(stack.STACKS)
    assert job["strategy"]["fail-fast"] is False  # both answers are wanted
    runs = [step.get("run") for step in job["steps"]]
    assert runs.count("python tools/test_stack.py ${{ matrix.stack }}") == 1
    assert "pip install -r requirements-test.txt" not in runs
    assert "continue-on-error" not in job
    assert not [step for step in job["steps"] if "continue-on-error" in step]


def test_dependabot_leaves_alone_what_home_assistant_dictates(
    stack: ModuleType,
) -> None:
    """The newest on the package index is not the version to test with.

    Nine pull requests for these were raised and none could be merged; the
    list of what to leave alone follows the script's own.
    """
    updates = _yaml(".github/dependabot.yml")["updates"]
    (pip,) = [entry for entry in updates if entry["package-ecosystem"] == "pip"]

    assert {entry["dependency-name"] for entry in pip["ignore"]} == {
        "pytest-homeassistant-custom-component",
        *stack.DICTATED,
        *stack.COMPANIONS,
    }


@pytest.mark.parametrize(
    ("workflow", "jobs"),
    [("test.yml", ["test"]), ("validate.yml", ["hassfest", "hacs"])],
)
def test_a_commit_is_checked_once_whichever_way_it_arrived(
    workflow: str, jobs: list[str]
) -> None:
    """A push and a pull request for the same commit are one run, not two.

    The pull_request run is the one skipped, and only when its branch is in
    this repository: a branch nobody opened a pull request for has only the
    push, and a fork has only the pull request.
    """
    loaded = _yaml(f".github/workflows/{workflow}")

    assert list(loaded["jobs"]) == jobs
    for name in jobs:
        assert " ".join(loaded["jobs"][name]["if"].split()) == _ONCE
